apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: praful-demo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/prafulkharat23/demo-argocd.git
    targetRevision: HEAD
    path: k8s-manifest
  destination:
    server: https://kubernetes.default.svc
    namespace: praful-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - syncTimeout=100s # Sets the sync timeout to 300 seconds
